#!/bin/bash

# 自动生成 index.html，列出所有可用的演示文稿

INDEX_FILE="index.html"

# 演示文稿描述映射（从文件名到描述）
declare -A DESCRIPTIONS=(
    ["presentation1"]="Motivation"
    ["presentation2"]="Quadruped Model"
    ["presentation3"]="Biped Model"
    ["presentation4"]="Research Proposal"
)

# 演示文稿显示名称映射
declare -A DISPLAY_NAMES=(
    ["presentation1"]="Pre 1"
    ["presentation2"]="Pre 2"
    ["presentation3"]="Pre 3"
    ["presentation4"]="Pre 4"
)

cat > "$INDEX_FILE" << 'EOF'
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>导盲机器人演示文稿</title>
    <style>
        body {
            font-family: 'Noto Sans SC', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background: #f5f5f5;
        }
        h1 {
            color: #A72335;
            border-bottom: 4px solid #A72335;
            padding-bottom: 10px;
        }
        .presentation-list {
            list-style: none;
            padding: 0;
        }
        .presentation-list li {
            margin: 15px 0;
            padding: 15px;
            background: white;
            border-left: 4px solid #D4AF37;
            border-radius: 4px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .presentation-list a {
            text-decoration: none;
            color: #A72335;
            font-weight: 600;
            font-size: 18px;
        }
        .presentation-list a:hover {
            text-decoration: underline;
        }
        .description {
            color: #666;
            margin-top: 5px;
            font-size: 14px;
        }
        .meta {
            color: #999;
            font-size: 12px;
            margin-top: 5px;
        }
    </style>
</head>
<body>
    <h1> My Pres</h1>
    
    <ul class="presentation-list">
EOF

# 查找所有 presentation*.html 文件并按名称排序
for html_file in presentation*.html; do
    if [ -f "$html_file" ]; then
        # 提取文件名（不含扩展名）
        filename=$(basename "$html_file" .html)
        
        # 获取显示名称，如果没有则使用默认格式
        display_name="${DISPLAY_NAMES[$filename]:-${filename/presentation/Pre }}"
        
        # 获取描述，如果没有则使用默认值
        description="${DESCRIPTIONS[$filename]:-Presentation}"
        
        # 获取文件修改时间
        if command -v stat >/dev/null 2>&1; then
            if [[ "$OSTYPE" == "darwin"* ]]; then
                # macOS
                mod_time=$(stat -f "%Sm" -t "%Y-%m-%d" "$html_file" 2>/dev/null || echo "")
            else
                # Linux
                mod_time=$(stat -c "%y" "$html_file" 2>/dev/null | cut -d' ' -f1 || echo "")
            fi
        else
            mod_time=""
        fi
        
        cat >> "$INDEX_FILE" << EOF
        <li>
            <a href="$html_file">$display_name</a>
            <div class="description">$description</div>
EOF
        
        if [ -n "$mod_time" ]; then
            cat >> "$INDEX_FILE" << EOF
            <div class="meta">Last updated: $mod_time</div>
EOF
        fi
        
        cat >> "$INDEX_FILE" << EOF
        </li>
EOF
    fi
done

cat >> "$INDEX_FILE" << 'EOF'
    </ul>
    
    <footer style="margin-top: 40px; color: #999; font-size: 12px;">
        <p>© 2025 Hong Kong Polytechnic University</p>
        <p>Generated by Marp | Auto-updated by GitHub Actions</p>
    </footer>
</body>
</html>
EOF

echo "Generated index.html with $(ls -1 presentation*.html 2>/dev/null | wc -l) presentation(s)"

